databases:
  - name: findash
    databaseName: findash
    user: findash


services:
  - type: web
    name: findash
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn findash.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: findash
          property: connectionString
      - key:
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4